# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.

# Testing tools configuration
[tool.coverage.run]
branch = true

[tool.coverage.report]
show_missing = true

[tool.pytest.ini_options]
minversion = "6.0"
log_cli_level = "INFO"
asyncio_mode = "auto"

# Formatting tools configuration
[tool.black]
line-length = 99
target-version = ["py38"]

[tool.isort]
profile = "black"

# Linting tools configuration
[tool.ruff]
line-length = 99
extend-exclude = ["__pycache__", "*.egg_info"]

[tool.ruff.lint]
select = ["E", "W", "F", "C", "N", "D", "I001"]
ignore = [
    "C408",
    "D107",
    "D203",
    "D213",
    "D401",
]
per-file-ignores = {"tests/*" = ["D100","D103"]}

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.mypy]
mypy_path = "src:lib"

[tool.codespell]
skip = ".git,.tox,build,lib,venv,htmlcov,.mypy_cache,icon.svg,.ruff_cache,.coverage,*.yaml"
